# Generated by Django 5.0.1 on 2024-02-07 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=30)),
                ('rating', models.DecimalField(decimal_places=1, max_digits=2)),
                ('latitude', models.FloatField()),
                ('longtitude', models.FloatField()),
                ('opening_time', models.TimeField()),
                ('closing_time', models.TimeField()),
                ('university', models.CharField(blank=True, choices=[('UNL', 'NOVA IMS'), ('ifgi', 'Münster'), ('UNL', 'Castellón')], max_length=4)),
                ('type_food', models.TextField(blank=True)),
                ('photo_main', models.ImageField(upload_to='photos/%Y/%m/%d')),
                ('photo_1', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d')),
                ('photo_2', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d')),
                ('photo_3', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d')),
                ('is_published', models.BooleanField(default=True)),
            ],
        ),
    ]
