# Generated by Django 5.0.1 on 2024-02-07 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='university',
            field=models.CharField(blank=True, choices=[('UNL', 'Universidade Nova de Lisboa'), ('ifgi', 'University of Münster'), ('UNL', 'Universitat Jaume I')], max_length=4),
        ),
    ]
